PAL = 1

#if PAL = 1
BLACK           = $00
WHITE           = $0E
RED             = $62
GREEN           = $56
BLUE            = $D6
YELL            = $2C
GREY            = $04
PURPLE          = $84
ORANGE          = $44
PINK            = $4C
LIGHTBLUE       = $D8
DARKGREEN       = $54
CYANGREEN	= $74
DARKBLUE        = $D2
LIGHTBROWN	= $26
DARKBROWN	= $24
MAGENTA		= $84
#endif

#if PAL = 0
BLACK           = $00
WHITE           = $0C
RED             = $42
GREEN           = $C6
BLUE            = $84
YELL            = $18
GREY            = $04
PURPLE          = $50
ORANGE          = $36
PINK            = $3C
LIGHTBLUE       = $7E
DARKBLUE        = $90	
DARKGREEN       = $D4
CYANGREEN	= $B4
LIGHTBROWN	= $2F
DARKBROWN	= $26
MAGENTA		= $54	
#endif

#if PAL = 1
VBLAN = 48
GRAPHICKERNEL = 228
OVERSCAN = 36
TIMER = 53
#endif

#if PAL = 0
VBLAN = 40
GRAPHICKERNEL = 192
OVERSCAN = 30
TIMER = 43
#endif

ROW = $80
TEMPVAR1 = $81
TEMPVAR2 = $82
GRTABLE = $83

HUHNX0	= $8F
HUHN_ADR_A0 = $90
HUHN_ADR_B0 = $91
HUHN_HEALTH_DIRECTION0 = $92

HUHNX1	= $93
HUHN_ADR_A1 = $94
HUHN_ADR_B1 = $95
HUHN_HEALTH_DIRECTION1 = $96

HUHNX2	= $97
HUHN_ADR_A2 = $98
HUHN_ADR_B2 = $99
HUHN_HEALTH_DIRECTION2 = $9A

HUHNX3	= $9B
HUHN_ADR_A3 = $9C
HUHN_ADR_B3 = $9D
HUHN_HEALTH_DIRECTION3 = $9E

HUHNX4	= $9F
HUHN_ADR_A4 = $A0
HUHN_ADR_B4 = $A1
HUHN_HEALTH_DIRECTION4 = $A2

HUHNX5	= $A3
HUHN_ADR_A5 = $A4
HUHN_ADR_B5 = $A5
HUHN_HEALTH_DIRECTION5 = $A6

HUHNX6	= $A7
HUHN_ADR_A6 = $A8
HUHN_ADR_B6 = $A9
HUHN_HEALTH_DIRECTION6 = $AA

HUHNX7	= $AB
HUHN_ADR_A7 = $AC
HUHN_ADR_B7 = $AD
HUHN_HEALTH_DIRECTION7 = $AE

HUHNX8	= $AF
HUHN_ADR_A8 = $B0
HUHN_ADR_B8 = $B1
HUHN_HEALTH_DIRECTION8 = $B2

HUHNX9	= $B3
HUHN_ADR_A9 = $B4
HUHN_ADR_B9 = $B5
HUHN_HEALTH_DIRECTION9 = $B6

GAMESTATUS = $B7
PLAYERX0 = $B8
PLAYERHMOVE0 = $B9
PLAYERY0 = $BA
PLAYERYTEMP0 = $BB
PISTOL = $BC
JOYSTICKMOVEDUP = $BD
JOYSTICKMOVEDDOWN = $BE
NTSCBREAKER = $BF
SCORE1 = $C0
SCORE2 = $C1
SCORE3 = $C2
RAND1 = $C3
RAND2 = $C4
CROSSREADY = $C7
CHICKENHIT = $C8
Xpos = $C9
Ypos = $CA
TIME1 = $C5
TIME2 = $C6
TIME3 = $CB
SOUNDTABLESELECTOR = $CC
SOUNDDELAYCOUNTER = $CD
SOUNDTABLEINDEX = $CE
SEASON = $CF
AMUNITION = $D0
